---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  progressDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: quay.io/waffleio/testapp-k8s:release
